openapi: 3.1.0
info:
  version: 1.0.0
  title: ASIC Sentry API Document
  contact:
    name: Nguyen Vinh Linh
    email: nguyenvinhlinh93@gmail.com
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
    altText: OpenAPI example logo
  description: >-
    This is API document for ASIC Sentry serving Remote Relay Controller(RRC)
servers:
  - url: http://asic_sentry:port/api/v1
paths:
  '/expected_status':
    $ref: 'paths/expected_status.yaml'

#  '/users/{username}':
#    $ref: 'paths/users_{username}.yaml'
  # '/user':
  #   $ref: 'paths/user.yaml'
  # '/user/list':
  #   $ref: 'paths/user-status.yaml'
  # /pathItem:
  #   $ref: paths/pathItem.yaml
  # /pathItemWithExamples:
  #   $ref: paths/pathItemWithExamples.yaml
  # '/echo':
  #   $ref: 'paths/echo.yaml'
components:
  securitySchemes:
    rrc_code:
      description: "It's a must to assign request header name `RRC_CODE`"
      type: apiKey
      in: header
      name: RRC_CODE
