openapi: 3.1.0
info:
  version: 1.0.0
  title: ASIC Sentry API Document
  contact:
    name: Nguyen Vinh Linh
    email: nguyenvinhlinh93@gmail.com
  x-logo:
    url: 'https://raw.githubusercontent.com/nguyenvinhlinh/asic_sentry_api_document/refs/heads/main/images/logo.png'
    altText: ASIC Sentry API Document
    href: http://asic-sentry-api-docs.hexalink.xyz
  description: >-
    This is API document for ASIC Sentry serving Remote Relay Controller(RRC)
servers:
  - url: http://asic_sentry:port/api/v1
paths:
  '/expected_status':
    $ref: 'paths/expected_status.yaml'
  '/asic_miner_log':
    $ref: 'paths/asic_miner_log.yaml'
components:
  securitySchemes:
    rrc_code:
      description: "It's a must to assign request header name `RRC_CODE`"
      type: apiKey
      in: header
      name: RRC_CODE
